# Rime default settings
# encoding: utf-8
# CC-BY-4.0

config_version: '0.40'

schema_list:
  - schema: tiger_code          # ğŸ¯Â·å•Â·å®˜æ–¹
  - schema: tiger_chord_popping # ğŸ¯Â·å•Â·å¹¶å‡»Â·é¡¶åŠŸ
  - schema: tiger_code_52p      # ğŸ¯Â·å•Â·äº”äºŒé¡¶
  - schema: tiger_code_53p      # ğŸ¯Â·å•Â·äº”ä¸‰é¡¶
  - schema: tiger_codes         # ğŸ¯Â·è¯Â·å®˜æ–¹
  - schema: tiger_oni           # ğŸ¯Â·è¯Â·é¬¼è™
  - schema: tiger_phrase        # ğŸ¯Â·å•å¥
  - schema: tiger_phrase_chord  # ğŸ¯Â·å•å¥Â·å¹¶å‡»
  - schema: tiger_phrases       # ğŸ¯Â·è¯å¥
  - schema: easy_en             # æ™ºèƒ½è‹±æ–‡

switcher:
  caption: "ã€”æ–¹æ¡ˆé¸å–®ã€•"
  hotkeys:
    - "Control+grave"
    - "Control+F8"
  save_options:
    - full_shape
    - ascii_punct
    - traditionalization
    - emoji
    - extended_char
    - mars
    - prediction
    - tiger_spelling.off
    - tiger_spelling.lv1
    - tiger_spelling.lv2
    - tiger_spelling.lv3
    - tiger_spelling.lv4
  fold_options: true
  abbreviate_options: true
  option_list_separator: 'ï¼'

menu:
  #alternative_select_labels: [ â‘´, â‘µ, â‘¶, â‘·, â‘¸, â‘¹, â‘º, â‘», â‘¼, â‘½ ]
  alternative_select_labels: [ ã€¡, ã€¢, ã€£, ã€¤, ã€¥, ã€¦, ã€§, ã€¨, ã€©, ã€¸ ]
  #alternative_select_labels: [ Î±, Î², Î³, Î´, Îµ, Î¶, Î·, Î¸, Î¹, Îº ]
  page_size: 5

punctuator:
  __include: tiger:/punctuator

key_binder:
  import_preset: default
  bindings:
    __patch:
      - tiger:/keys/emacs_mode
      - tiger:/keys/tab
      - tiger:/keys/page_up_down
      #- tiger:/keys/selector
      - tiger:/keys/options_toggle

recognizer:
  patterns:
    #email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    #uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    #url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: noop
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    # Shift_L: commit_code
    # Shift_R: commit_text
